# Generated by Django 5.2.16 on 2026-08-05 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Responsable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("correo", models.EmailField(max_length=254)),
                ("cargo", models.CharField(blank=True, max_length=150)),
                ("dependencia", models.CharField(max_length=150)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Responsable",
                "verbose_name_plural": "Responsables",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Comunicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("ENTRADA", "Entrada"), ("SALIDA", "Salida")],
                        max_length=20,
                    ),
                ),
                (
                    "radicado",
                    models.CharField(
                        blank=True, db_index=True, max_length=30, null=True, unique=True
                    ),
                ),
                (
                    "consecutivo",
                    models.CharField(
                        blank=True, db_index=True, max_length=30, null=True, unique=True
                    ),
                ),
                ("fecha", models.DateTimeField(verbose_name="Fecha del correo")),
                ("fecha_recepcion", models.DateTimeField(auto_now_add=True)),
                ("remitente", models.CharField(max_length=250)),
                ("destinatarios", models.TextField(blank=True)),
                ("copia", models.TextField(blank=True)),
                ("asunto", models.CharField(max_length=500)),
                ("mensaje", models.TextField()),
                ("referencia", models.CharField(blank=True, max_length=100)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("NUEVO", "Nuevo"),
                            ("RADICADO", "Radicado"),
                            ("DELEGADO", "Delegado"),
                            ("EN_PROCESO", "En Proceso"),
                            ("FINALIZADO", "Finalizado"),
                        ],
                        db_index=True,
                        default="NUEVO",
                        max_length=20,
                    ),
                ),
                ("remitido_transaccion", models.BooleanField(default=False)),
                ("fecha_remision", models.DateTimeField(blank=True, null=True)),
                (
                    "estado_flujo",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrador"),
                            ("TRANSACCION", "Transacción"),
                            ("FUNCIONARIO", "Funcionario"),
                            ("FINALIZADO", "Finalizado"),
                        ],
                        db_index=True,
                        default="ADMIN",
                        max_length=20,
                    ),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("BAJA", "Baja"),
                            ("NORMAL", "Normal"),
                            ("ALTA", "Alta"),
                            ("URGENTE", "Urgente"),
                        ],
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "gmail_id",
                    models.CharField(blank=True, db_index=True, max_length=200),
                ),
                (
                    "thread_id",
                    models.CharField(blank=True, db_index=True, max_length=200),
                ),
                ("tiene_adjuntos", models.BooleanField(default=False)),
                ("es_leido", models.BooleanField(default=False)),
                ("es_archivado", models.BooleanField(default=False)),
                ("etiqueta", models.CharField(blank=True, max_length=100)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "evidencia",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="evidencias/",
                        verbose_name="PDF Evidencia",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="comunicaciones.responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "ComunicaciÃ³n",
                "verbose_name_plural": "Comunicaciones",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Adjunto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=250)),
                ("archivo", models.FileField(upload_to="adjuntos/")),
                ("tamano", models.PositiveIntegerField()),
                ("tipo", models.CharField(max_length=100)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "comunicacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjuntos",
                        to="comunicaciones.comunicacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adjunto",
                "verbose_name_plural": "Adjuntos",
            },
        ),
        migrations.CreateModel(
            name="Consecutivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consecutivo",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="Consecutivo",
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha")),
                (
                    "dirigido_a",
                    models.CharField(max_length=300, verbose_name="Dirigido a"),
                ),
                ("asunto", models.CharField(max_length=500)),
                ("funcionario_responsable", models.CharField(max_length=200)),
                ("caso_aranda", models.CharField(blank=True, max_length=200)),
                ("observaciones", models.TextField(blank=True)),
                ("fecha_envio", models.DateField(blank=True, null=True)),
                (
                    "tipo_archivo",
                    models.CharField(max_length=150, verbose_name="Tipo Archivo / TRD"),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        max_length=300, verbose_name="Ubicación (Carpeta Archivo)"
                    ),
                ),
                (
                    "archivado",
                    models.CharField(
                        choices=[("SI", "SI"), ("NO", "NO")], default="NO", max_length=2
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Consecutivo",
                "verbose_name_plural": "Consecutivos",
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Historial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accion", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "comunicacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comunicaciones.comunicacion",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial",
                "verbose_name_plural": "Historial",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Regla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("palabra", models.CharField(max_length=100, unique=True)),
                ("activa", models.BooleanField(default=True)),
                (
                    "responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comunicaciones.responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regla",
                "verbose_name_plural": "Reglas",
                "ordering": ["palabra"],
            },
        ),
    ]
