# Generated by Django 5.2.16 on 2026-07-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comunicaciones", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comunicacion",
            options={
                "ordering": ["-fecha"],
                "verbose_name": "ComunicaciÃ³n",
                "verbose_name_plural": "Comunicaciones",
            },
        ),
        migrations.AlterField(
            model_name="responsable",
            name="correo",
            field=models.EmailField(max_length=254),
        ),
    ]
