# Generated by Django 5.2.16 on 2026-08-05 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comunicaciones", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comunicacion",
            options={
                "ordering": ["-fecha"],
                "verbose_name": "Comunicación",
                "verbose_name_plural": "Comunicaciones",
            },
        ),
    ]
