# Generated by Django 5.2.16 on 2026-07-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comunicaciones", "0002_alter_comunicacion_options_alter_responsable_correo"),
    ]

    operations = [
        migrations.AddField(
            model_name="comunicacion",
            name="evidencia",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="evidencias/",
                verbose_name="PDF Evidencia",
            ),
        ),
    ]
