# Generated by Django 5.2.16 on 2026-08-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comunicaciones", "0002_alter_comunicacion_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="comunicacion",
            name="drive_fecha_subida",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha subida a Drive"
            ),
        ),
        migrations.AddField(
            model_name="comunicacion",
            name="drive_file_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=200,
                null=True,
                verbose_name="ID archivo Google Drive",
            ),
        ),
        migrations.AddField(
            model_name="comunicacion",
            name="drive_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="URL Google Drive"
            ),
        ),
    ]
