# Generated by Django 5.2.16 on 2026-08-10 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comunicaciones", "0003_comunicacion_drive_fecha_subida_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="responsable",
            name="usuario",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responsable",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
