# Generated by Django 5.2.16 on 2026-08-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comunicaciones", "0003_comunicacion_evidencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="comunicacion",
            name="estado_flujo",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrador"),
                    ("TRANSACCION", "Transacción"),
                    ("FUNCIONARIO", "Funcionario"),
                    ("FINALIZADO", "Finalizado"),
                ],
                db_index=True,
                default="ADMIN",
                max_length=20,
            ),
        ),
    ]
