# Generated by Django 5.2.16 on 2026-08-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comunicaciones", "0004_comunicacion_estado_flujo"),
    ]

    operations = [
        migrations.AddField(
            model_name="comunicacion",
            name="fecha_remision",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comunicacion",
            name="remitido_transaccion",
            field=models.BooleanField(default=False),
        ),
    ]
