# Generated by Django 5.2.16 on 2026-08-11 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comunicaciones", "0005_alter_responsable_usuario"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="consecutivo",
            name="consecutivo",
            field=models.CharField(
                editable=False, max_length=20, verbose_name="Consecutivo"
            ),
        ),
        migrations.AlterField(
            model_name="consecutivo",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consecutivos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="consecutivo",
            constraint=models.UniqueConstraint(
                fields=("usuario", "consecutivo"), name="unique_consecutivo_por_usuario"
            ),
        ),
    ]
