# Generated by Django 5.2.16 on 2026-08-12 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "comunicaciones",
            "0006_alter_consecutivo_consecutivo_and_more",
        ),
        migrations.swappable_dependency(
            settings.AUTH_USER_MODEL
        ),
    ]

    operations = [

        # ==================================================
        # CREAR MODELO ASIGNACION
        # ==================================================

        migrations.CreateModel(
            name="Asignacion",
            fields=[

                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),

                (
                    "fecha",
                    models.DateTimeField(
                        auto_now_add=True
                    ),
                ),

                (
                    "activa",
                    models.BooleanField(
                        default=True
                    ),
                ),

                (
                    "observaciones",
                    models.TextField(
                        blank=True
                    ),
                ),

            ],

            options={
                "ordering": ["-fecha"],
            },
        ),

        # ==================================================
        # COMUNICACION
        # ==================================================

        migrations.AddField(
            model_name="asignacion",
            name="comunicacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asignaciones",
                to="comunicaciones.comunicacion",
            ),
        ),

        # ==================================================
        # RESPONSABLE
        # ==================================================

        migrations.AddField(
            model_name="asignacion",
            name="responsable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asignaciones",
                to="comunicaciones.responsable",
            ),
        ),

        # ==================================================
        # USUARIO QUE REALIZA LA ASIGNACION
        # ==================================================

        migrations.AddField(
            model_name="asignacion",
            name="usuario_asignador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),

    ]